[package]
name = "tendermint-example"
version = "0.1.0"
authors = ["phqb <bao.phan@kyber.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abci = "0.7.1"
byteorder = "1.3.4"
env_logger = "0.8.2"
